### ISSUE TITLE
E-Mail-Versand mit Authentication ermöglichen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/opus4-common#66]
Für den Versand von E-Mails wird `Zend_Mail_Transport_Smtp` von ZF1 verwendet. Für diese Klasse kann auch Authentication konfiguriert werden.

https://framework.zend.com/manual/1.12/en/zend.mail.smtp-authentication.html

Um die vollständige Konfiguration zu unterstützen muss die Klasse `Opus\Common\Mail\Transport` angepasst werden.

Ob die ZF1 Implementation aktuell noch mit Authentication und SSL funktioniert, muss nach den Anpassungen geprüft werden. Mit dem Umstieg auf Laminas wird OPUS 4 dann die aktuellste Implementation verwenden.

**Comment by j3nsch** [comment]
Es wurde Support für folgende Optionen hinzugefügt:

```
mail.opus.auth =
mail.opus.username =
main.opus.password =
main.opus.ssl =
```

Diese Optionen können zur Konfigurationsdatei `config.ini` hinzugefügt werden. Mehr Informationen zu den Optionen finden sich in der Zend Framework 1 (ZF1) Dokumentation.

https://framework.zend.com/manual/1.12/en/zend.mail.smtp-authentication.html

Die Funktionalität, basierend auf ZF1, ist nicht weiter getestet und wird später mit Laminas ersetzt. Um die neue Version von **opus4-common** zu nutzen, muss sie mit `composer update` instaliert werden.

**Comment by vgerlach** [comment]
main.opus.password =
main.opus.ssl =

sollten vermutlich

**mail**.opus.password =
**mail**.opus.ssl =

heißen.

**Comment by j3nsch** [comment]
Danke, oben im Kommentar auch korrigiert.
