### ISSUE TITLE
Methode zur Abfrage von Konfigurationsoptionen von Application nach Common verschieben

### ISSUE THREAD

**Issue by extracts** [OPUS4/opus4-common#93]
Die Application-Methode [`Application_Configuration->getValueFromConfig()`](https://github.com/OPUS4/application/blob/master/library/Application/Configuration.php#L271) ermöglicht es, in der `Config.ini` gesetzte Werte auszulesen. Um diese Funktionalität auch in anderen Modulen (z.B. `opus4-pdf`) verfügbar zu machen, sollte diese Methode (als auch die entsprechende `Application_Configuration->setValueInConfig()` Methode) in die Basis-Klasse (`Opus\Common\Config`) verschoben werden.

**Comment by j3nsch** [comment]
Ja, nur direkte Tests der beiden statischen Funktionen verschieben.

**Comment by j3nsch** [comment]
Das sollte ja erledigt sein.
